name: Go Release Builder (SLSA)

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        arch: [ amd64, arm64 ]
        exclude:
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: arm64
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0
    with:
      go-version: 1.19
      config-file: .slsa-goreleaser/${{matrix.os}}-${{matrix.arch}}.yml
      private-repository: true
